use crate::types::{word_type::*, Reason};
use std::collections::HashMap;
use std::sync::OnceLock;

pub struct DeinflectRule {
    pub from: &'static str,
    pub to: &'static str,
    pub from_type: u16,
    pub to_type: u16,
    pub reasons: &'static [Reason],
}

pub static RULES: &[DeinflectRule] = &[
    // -------------- 7 --------------
    DeinflectRule {
        from: "ていらっしゃい",
        to: "",
        from_type: INITIAL,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous, Reason::Imperative],
    },
    DeinflectRule {
        from: "ていらっしゃる",
        to: "",
        from_type: GODAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous],
    },
    DeinflectRule {
        from: "でいらっしゃい",
        to: "",
        from_type: INITIAL,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous, Reason::Imperative],
    },
    DeinflectRule {
        from: "でいらっしゃる",
        to: "",
        from_type: GODAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous],
    },
    // -------------- 6 --------------
    DeinflectRule {
        from: "いらっしゃい",
        to: "いらっしゃる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "いらっしゃい",
        to: "いらっしゃる",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "くありません",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::PoliteNegative],
    },
    DeinflectRule {
        from: "ざるをえない",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "ざるを得ない",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "ませんでした",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::PolitePastNegative],
    },
    DeinflectRule {
        from: "てらっしゃい",
        to: "",
        from_type: INITIAL,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous, Reason::Imperative],
    },
    DeinflectRule {
        from: "てらっしゃい",
        to: "てらっしゃる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "てらっしゃる",
        to: "",
        from_type: GODAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous],
    },
    DeinflectRule {
        from: "でらっしゃい",
        to: "",
        from_type: INITIAL,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous, Reason::Imperative],
    },
    DeinflectRule {
        from: "でらっしゃい",
        to: "でらっしゃる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "でらっしゃる",
        to: "",
        from_type: GODAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Respectful, Reason::Continuous],
    },
    // -------------- 5 --------------
    DeinflectRule {
        from: "おっしゃい",
        to: "おっしゃる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "おっしゃい",
        to: "おっしゃる",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "ざるえない",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "ざる得ない",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "ざるをえぬ",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "ざるを得ぬ",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    // -------------- 4 --------------
    DeinflectRule {
        from: "かったら",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Tara],
    },
    DeinflectRule {
        from: "かったり",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Tari],
    },
    DeinflectRule {
        from: "ください",
        to: "くださる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "ください",
        to: "くださる",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "こさせる",
        to: "くる",
        from_type: ICHIDAN_VERB,
        to_type: KURU_VERB,
        reasons: &[Reason::Causative],
    },
    DeinflectRule {
        from: "こられる",
        to: "くる",
        from_type: ICHIDAN_VERB,
        to_type: KURU_VERB,
        reasons: &[Reason::PotentialOrPassive],
    },
    DeinflectRule {
        from: "さないで",
        to: "する",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::NegativeTe],
    },
    DeinflectRule {
        from: "ざるえぬ",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "ざる得ぬ",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::ZaruWoEnai],
    },
    DeinflectRule {
        from: "しないで",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::NegativeTe],
    },
    DeinflectRule {
        from: "しさせる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Causative],
    },
    DeinflectRule {
        from: "しられる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::PotentialOrPassive],
    },
    DeinflectRule {
        from: "せさせる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Causative],
    },
    DeinflectRule {
        from: "せられる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::PotentialOrPassive],
    },
    DeinflectRule {
        from: "ぜさせる",
        to: "ずる",
        from_type: ICHIDAN_VERB,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Causative],
    },
    DeinflectRule {
        from: "ぜられる",
        to: "ずる",
        from_type: ICHIDAN_VERB,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::PotentialOrPassive],
    },
    DeinflectRule {
        from: "たゆたう",
        to: "たゆたう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "たゆとう",
        to: "たゆとう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "のたまう",
        to: "のたまう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "のたもう",
        to: "のたもう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ましたら",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Polite, Reason::Tara],
    },
    DeinflectRule {
        from: "ましたり",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Polite, Reason::Tari],
    },
    DeinflectRule {
        from: "ましょう",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::PoliteVolitional],
    },
    // -------------- 3 --------------
    DeinflectRule {
        from: "いたす",
        to: "",
        from_type: GODAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::Humble],
    },
    DeinflectRule {
        from: "いたす",
        to: "",
        from_type: GODAN_VERB,
        to_type: NOUN_VS,
        reasons: &[Reason::SuruNoun, Reason::Humble],
    },
    DeinflectRule {
        from: "かった",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Past],
    },
    DeinflectRule {
        from: "下さい",
        to: "下さる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "下さい",
        to: "下さる",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "くない",
        to: "い",
        from_type: I_ADJ,
        to_type: I_ADJ,
        reasons: &[Reason::Negative],
    },
    DeinflectRule {
        from: "ければ",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "こよう",
        to: "くる",
        from_type: INITIAL,
        to_type: KURU_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "これる",
        to: "くる",
        from_type: ICHIDAN_VERB,
        to_type: KURU_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "来れる",
        to: "来る",
        from_type: ICHIDAN_VERB,
        to_type: KURU_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "來れる",
        to: "來る",
        from_type: ICHIDAN_VERB,
        to_type: KURU_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "ござい",
        to: "ござる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "ご座い",
        to: "ご座る",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "御座い",
        to: "御座る",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "させる",
        to: "る",
        from_type: ICHIDAN_VERB,
        to_type: ICHIDAN_VERB | KURU_VERB,
        reasons: &[Reason::Causative],
    },
    DeinflectRule {
        from: "させる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SURU_VERB,
        reasons: &[Reason::Causative],
    },
    DeinflectRule {
        from: "さない",
        to: "する",
        from_type: I_ADJ,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Negative],
    },
    DeinflectRule {
        from: "される",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::CausativePassive],
    },
    DeinflectRule {
        from: "される",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SURU_VERB,
        reasons: &[Reason::Passive],
    },
    DeinflectRule {
        from: "しうる",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::EruUru],
    },
    DeinflectRule {
        from: "しえる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SURU_VERB,
        reasons: &[Reason::EruUru],
    },
    DeinflectRule {
        from: "しない",
        to: "する",
        from_type: I_ADJ,
        to_type: SURU_VERB,
        reasons: &[Reason::Negative],
    },
    DeinflectRule {
        from: "しよう",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "じゃう",
        to: "",
        from_type: GODAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Chau],
    },
    DeinflectRule {
        from: "すぎる",
        to: "い",
        from_type: ICHIDAN_VERB,
        to_type: I_ADJ,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "すぎる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "過ぎる",
        to: "い",
        from_type: ICHIDAN_VERB,
        to_type: I_ADJ,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "過ぎる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "ずれば",
        to: "ずる",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Ba],
    },
    DeinflectRule {
        from: "たまう",
        to: "たまう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "たもう",
        to: "たもう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "揺蕩う",
        to: "揺蕩う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ちゃう",
        to: "",
        from_type: GODAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Chau],
    },
    DeinflectRule {
        from: "ている",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Continuous],
    },
    DeinflectRule {
        from: "ておる",
        to: "",
        from_type: GODAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::HumbleOrKansaiDialect, Reason::Continuous],
    },
    DeinflectRule {
        from: "でいる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Continuous],
    },
    DeinflectRule {
        from: "でおる",
        to: "",
        from_type: GODAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::HumbleOrKansaiDialect, Reason::Continuous],
    },
    DeinflectRule {
        from: "できる",
        to: "する",
        from_type: ICHIDAN_VERB,
        to_type: SURU_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "ないで",
        to: "",
        from_type: INITIAL,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::NegativeTe],
    },
    DeinflectRule {
        from: "なさい",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Respectful, Reason::Imperative],
    },
    DeinflectRule {
        from: "なさい",
        to: "なさる",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "なさい",
        to: "なさる",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "なさる",
        to: "",
        from_type: GODAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::Respectful],
    },
    DeinflectRule {
        from: "なさる",
        to: "",
        from_type: GODAN_VERB,
        to_type: NOUN_VS,
        reasons: &[Reason::SuruNoun, Reason::Respectful],
    },
    DeinflectRule {
        from: "になる",
        to: "",
        from_type: GODAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::Respectful],
    },
    DeinflectRule {
        from: "になる",
        to: "",
        from_type: GODAN_VERB,
        to_type: NOUN_VS,
        reasons: &[Reason::SuruNoun, Reason::Respectful],
    },
    DeinflectRule {
        from: "ました",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::PolitePast],
    },
    DeinflectRule {
        from: "まして",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Polite, Reason::Te],
    },
    DeinflectRule {
        from: "ません",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::PoliteNegative],
    },
    DeinflectRule {
        from: "られる",
        to: "る",
        from_type: ICHIDAN_VERB,
        to_type: ICHIDAN_VERB | KURU_VERB,
        reasons: &[Reason::PotentialOrPassive],
    },
    // -------------- 2 --------------
    DeinflectRule {
        from: "致す",
        to: "",
        from_type: GODAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::Humble],
    },
    DeinflectRule {
        from: "致す",
        to: "",
        from_type: GODAN_VERB,
        to_type: NOUN_VS,
        reasons: &[Reason::SuruNoun, Reason::Humble],
    },
    DeinflectRule {
        from: "えば",
        to: "う",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "える",
        to: "う",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "得る",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: MASU_STEM,
        reasons: &[Reason::EruUru],
    },
    DeinflectRule {
        from: "おう",
        to: "う",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "仰い",
        to: "仰る",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "仰い",
        to: "仰る",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "くて",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Te],
    },
    DeinflectRule {
        from: "けば",
        to: "く",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "げば",
        to: "ぐ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "ける",
        to: "く",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "げる",
        to: "ぐ",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "こい",
        to: "くる",
        from_type: INITIAL,
        to_type: KURU_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "こう",
        to: "く",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "ごう",
        to: "ぐ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "しろ",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "さず",
        to: "する",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Zu],
    },
    DeinflectRule {
        from: "すぎ",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "すぎ",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "過ぎ",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "過ぎ",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Sugiru],
    },
    DeinflectRule {
        from: "する",
        to: "",
        from_type: SURU_VERB,
        to_type: NOUN_VS,
        reasons: &[Reason::SuruNoun],
    },
    DeinflectRule {
        from: "せず",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::Zu],
    },
    DeinflectRule {
        from: "せぬ",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::Negative],
    },
    DeinflectRule {
        from: "せん",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::Negative],
    },
    DeinflectRule {
        from: "せば",
        to: "す",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "せば",
        to: "する",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Ba],
    },
    DeinflectRule {
        from: "せよ",
        to: "する",
        from_type: INITIAL,
        to_type: SURU_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "せる",
        to: "す",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "せる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::Causative],
    },
    DeinflectRule {
        from: "ぜず",
        to: "ずる",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Zu],
    },
    DeinflectRule {
        from: "ぜぬ",
        to: "ずる",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Negative],
    },
    DeinflectRule {
        from: "ぜよ",
        to: "ずる",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Imperative],
    },
    DeinflectRule {
        from: "そう",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Sou],
    },
    DeinflectRule {
        from: "そう",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Sou],
    },
    DeinflectRule {
        from: "そう",
        to: "す",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "そう",
        to: "する",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Volitional],
    },
    DeinflectRule {
        from: "たい",
        to: "",
        from_type: I_ADJ,
        to_type: MASU_STEM,
        reasons: &[Reason::Tai],
    },
    DeinflectRule {
        from: "たら",
        to: "",
        from_type: INITIAL,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Tara],
    },
    DeinflectRule {
        from: "だら",
        to: "",
        from_type: INITIAL,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Tara],
    },
    DeinflectRule {
        from: "たり",
        to: "",
        from_type: INITIAL,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Tari],
    },
    DeinflectRule {
        from: "だり",
        to: "",
        from_type: INITIAL,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Tari],
    },
    DeinflectRule {
        from: "てば",
        to: "つ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "てる",
        to: "つ",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "てる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Continuous],
    },
    DeinflectRule {
        from: "でる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Continuous],
    },
    DeinflectRule {
        from: "とう",
        to: "つ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "とく",
        to: "",
        from_type: GODAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Toku],
    },
    DeinflectRule {
        from: "とる",
        to: "",
        from_type: GODAN_VERB,
        to_type: TA_TE_STEM,
        reasons: &[Reason::HumbleOrKansaiDialect, Reason::Continuous],
    },
    DeinflectRule {
        from: "どく",
        to: "",
        from_type: GODAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Toku],
    },
    DeinflectRule {
        from: "どる",
        to: "",
        from_type: GODAN_VERB,
        to_type: DA_DE_STEM,
        reasons: &[Reason::HumbleOrKansaiDialect, Reason::Continuous],
    },
    DeinflectRule {
        from: "ない",
        to: "",
        from_type: I_ADJ,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::Negative],
    },
    DeinflectRule {
        from: "ねば",
        to: "ぬ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "ねる",
        to: "ぬ",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "のう",
        to: "ぬ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "べば",
        to: "ぶ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "べる",
        to: "ぶ",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "ぼう",
        to: "ぶ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "ます",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Polite],
    },
    DeinflectRule {
        from: "ませ",
        to: "",
        from_type: INITIAL,
        to_type: MASU_STEM,
        reasons: &[Reason::Polite, Reason::Imperative],
    },
    DeinflectRule {
        from: "めば",
        to: "む",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "める",
        to: "む",
        from_type: ICHIDAN_VERB,
        to_type: GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "もう",
        to: "む",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "よう",
        to: "る",
        from_type: INITIAL,
        to_type: ICHIDAN_VERB | KURU_VERB,
        reasons: &[Reason::Volitional],
    },
    DeinflectRule {
        from: "れば",
        to: "る",
        from_type: INITIAL,
        to_type: ICHIDAN_VERB | GODAN_VERB | KURU_VERB | SURU_VERB,
        reasons: &[Reason::Ba],
    },
    DeinflectRule {
        from: "れる",
        to: "る",
        from_type: ICHIDAN_VERB,
        to_type: ICHIDAN_VERB | GODAN_VERB,
        reasons: &[Reason::Potential],
    },
    DeinflectRule {
        from: "れる",
        to: "",
        from_type: ICHIDAN_VERB,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::Passive],
    },
    DeinflectRule {
        from: "ろう",
        to: "る",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Volitional],
    },
    // Irregular て-form stems
    DeinflectRule {
        from: "いっ",
        to: "いく",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "おう",
        to: "おう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "こう",
        to: "こう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "そう",
        to: "そう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "とう",
        to: "とう",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "行っ",
        to: "行く",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "逝っ",
        to: "逝く",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "往っ",
        to: "往く",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "請う",
        to: "請う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "乞う",
        to: "乞う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "恋う",
        to: "恋う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "問う",
        to: "問う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "負う",
        to: "負う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "沿う",
        to: "沿う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "添う",
        to: "添う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "副う",
        to: "副う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "厭う",
        to: "厭う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "給う",
        to: "給う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "賜う",
        to: "賜う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "宣う",
        to: "宣う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "曰う",
        to: "曰う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    // -------------- 1 --------------
    DeinflectRule {
        from: "い",
        to: "う",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "い",
        to: "く",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "い",
        to: "ぐ",
        from_type: DA_DE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "い",
        to: "る",
        from_type: INITIAL,
        to_type: KURU_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "え",
        to: "う",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "か",
        to: "く",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "が",
        to: "ぐ",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "き",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Ki],
    },
    DeinflectRule {
        from: "き",
        to: "く",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "き",
        to: "くる",
        from_type: TA_TE_STEM,
        to_type: KURU_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "き",
        to: "くる",
        from_type: MASU_STEM,
        to_type: KURU_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "ぎ",
        to: "ぐ",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "く",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Adv],
    },
    DeinflectRule {
        from: "け",
        to: "く",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "げ",
        to: "ぐ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "こ",
        to: "くる",
        from_type: IRREALIS_STEM,
        to_type: KURU_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "さ",
        to: "い",
        from_type: INITIAL,
        to_type: I_ADJ,
        reasons: &[Reason::Noun],
    },
    DeinflectRule {
        from: "さ",
        to: "す",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "し",
        to: "す",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "し",
        to: "する",
        from_type: MASU_STEM,
        to_type: SURU_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "し",
        to: "す",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "し",
        to: "する",
        from_type: TA_TE_STEM,
        to_type: SURU_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ず",
        to: "",
        from_type: INITIAL,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::Zu],
    },
    DeinflectRule {
        from: "せ",
        to: "す",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "せ",
        to: "する",
        from_type: INITIAL,
        to_type: SPECIAL_SURU_VERB,
        reasons: &[Reason::Irregular, Reason::Imperative],
    },
    DeinflectRule {
        from: "た",
        to: "つ",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "た",
        to: "",
        from_type: INITIAL,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Past],
    },
    DeinflectRule {
        from: "だ",
        to: "",
        from_type: INITIAL,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Past],
    },
    DeinflectRule {
        from: "ち",
        to: "つ",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "っ",
        to: "う",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "っ",
        to: "つ",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "っ",
        to: "る",
        from_type: TA_TE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "て",
        to: "",
        from_type: INITIAL,
        to_type: TA_TE_STEM,
        reasons: &[Reason::Te],
    },
    DeinflectRule {
        from: "て",
        to: "つ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "で",
        to: "",
        from_type: INITIAL,
        to_type: DA_DE_STEM,
        reasons: &[Reason::Te],
    },
    DeinflectRule {
        from: "な",
        to: "ぬ",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "な",
        to: "",
        from_type: INITIAL,
        to_type: ICHIDAN_VERB | GODAN_VERB | KURU_VERB | SURU_VERB,
        reasons: &[Reason::ImperativeNegative],
    },
    DeinflectRule {
        from: "に",
        to: "ぬ",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "ぬ",
        to: "",
        from_type: INITIAL,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::Negative],
    },
    DeinflectRule {
        from: "ね",
        to: "ぬ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "ば",
        to: "ぶ",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "び",
        to: "ぶ",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "べ",
        to: "ぶ",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "ま",
        to: "む",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "み",
        to: "む",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "め",
        to: "む",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "よ",
        to: "る",
        from_type: INITIAL,
        to_type: ICHIDAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "ら",
        to: "る",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "り",
        to: "る",
        from_type: MASU_STEM,
        to_type: GODAN_VERB,
        reasons: &[Reason::MasuStem],
    },
    DeinflectRule {
        from: "れ",
        to: "る",
        from_type: INITIAL,
        to_type: GODAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "ろ",
        to: "る",
        from_type: INITIAL,
        to_type: ICHIDAN_VERB,
        reasons: &[Reason::Imperative],
    },
    DeinflectRule {
        from: "わ",
        to: "う",
        from_type: IRREALIS_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ん",
        to: "ぬ",
        from_type: DA_DE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ん",
        to: "ぶ",
        from_type: DA_DE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ん",
        to: "む",
        from_type: DA_DE_STEM,
        to_type: GODAN_VERB,
        reasons: &[],
    },
    DeinflectRule {
        from: "ん",
        to: "",
        from_type: INITIAL,
        to_type: IRREALIS_STEM,
        reasons: &[Reason::Negative],
    },
];

static RULES_BY_ENDING: OnceLock<HashMap<&'static str, Vec<&'static DeinflectRule>>> =
    OnceLock::new();

/// Returns a map from ending string to rules that match it. Lazily initialized.
pub fn get_rules_by_ending() -> &'static HashMap<&'static str, Vec<&'static DeinflectRule>> {
    RULES_BY_ENDING.get_or_init(|| {
        let mut map: HashMap<&'static str, Vec<&'static DeinflectRule>> = HashMap::new();
        for rule in RULES {
            map.entry(rule.from).or_default().push(rule);
        }
        map
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rule_count() {
        assert_eq!(RULES.len(), 241);
    }

    #[test]
    fn test_rules_by_ending_populated() {
        let map = get_rules_by_ending();
        assert!(map.contains_key("ます"));
        assert!(map.contains_key("た"));
        assert!(map.contains_key("て"));
    }
}
